import { Team } from "./team.model";

export const TEAMS: Team[] = [
  new Team(0, "Brazil", 1837.56, "https://www.worldometers.info/img/flags/br-flag.gif"),
  new Team(1, "Belgium", 1821.92, "https://www.worldometers.info/img/flags/be-flag.gif"),
  new Team(2, "Argentina", 1770.65, "https://www.worldometers.info/img/flags/ar-flag.gif"),
  new Team(3, "France", 1764.85, "https://www.worldometers.info/img/flags/fr-flag.gif"),
  new Team(4, "Denmark", 1665.47, "https://www.worldometers.info/img/flags/da-flag.gif"),
  new Team(5, "Spain", 1716.93, "https://www.worldometers.info/img/flags/sp-flag.gif"),
  new Team(6, "Portugal", 1678.65, "https://www.worldometers.info/img/flags/po-flag.gif"),
  new Team(7, "Germany", 1658.96, "https://www.worldometers.info/img/flags/gm-flag.gif"),
  new Team(8, "England", 1737.46, "https://flagpedia.net/data/flags/h80/gb-eng.webp"),
  new Team(9, "Qatar", 1441.41, "https://www.worldometers.info/img/flags/qa-flag.gif"),
  new Team(10, "Mexico", 1649.57, "https://www.worldometers.info/img/flags/mx-flag.gif"),
  new Team(11, "Netherlands", 1679.41, "https://www.worldometers.info/img/flags/nl-flag.gif"),
  new Team(12, "Uruguay", 1643.71, "https://www.worldometers.info/img/flags/uy-flag.gif"),
  new Team(13, "Switzerland", 1621.43, "https://www.worldometers.info/img/flags/sz-flag.gif"),
  new Team(14, "USA", 1635.01, "https://www.worldometers.info/img/flags/us-flag.gif"),
  new Team(15, "Croatia", 1632.15, "https://www.worldometers.info/img/flags/hr-flag.gif"),
  new Team(16, "Senegal", 1593.45, "https://www.worldometers.info/img/flags/sg-flag.gif"),
  new Team(17, "Iran", 1558.64, "https://www.worldometers.info/img/flags/ir-flag.gif"),
  new Team(18, "Japan", 1552.77, "https://www.worldometers.info/img/flags/ja-flag.gif"),
  new Team(19, "Morocco", 1558.9, "https://www.worldometers.info/img/flags/mo-flag.gif"),
  new Team(20, "Serbia", 1549.53, "https://www.worldometers.info/img/flags/ri-flag.gif"),
  new Team(21, "Poland", 1546.18, "https://www.worldometers.info/img/flags/pl-flag.gif"),
  new Team(22, "South Korea", 1526.2, "https://www.worldometers.info/img/flags/ks-flag.gif"),
  new Team(23, "Tunisia", 1507.86, "https://www.worldometers.info/img/flags/ts-flag.gif"),
  new Team(24, "Cameroon", 1484.95, "https://www.worldometers.info/img/flags/cm-flag.gif"),
  new Team(25, "Canada", 1473.82, "https://www.worldometers.info/img/flags/ca-flag.gif"),
  new Team(26, "Ecuador", 1463.74, "https://www.worldometers.info/img/flags/ec-flag.gif"),
  new Team(27, "Saudi Arabia", 1435.74, "https://www.worldometers.info/img/flags/sa-flag.gif"),
  new Team(28, "Ghana", 1389.68, "https://www.worldometers.info/img/flags/gh-flag.gif"),
  new Team(29, "Wales", 1582.13, "https://flagpedia.net/data/flags/h80/gb-wls.webp"),
  new Team(30, "Costa Rica", 1500.06, "https://www.worldometers.info/img/flags/cs-flag.gif"),
  new Team(31, "Australia", 1483.73, "https://www.worldometers.info/img/flags/as-flag.gif")
];
